---
title: Crypto Coins Now
timezone: UTC
collections:
  coins:
    title: Coins
    output: true
    permalink: "/coins/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: email@cryptocoinsnow.org
description: Cryptocurrencies latest streaming pricing data
baseurl: '/coins'
url: 
twitter_username: coingecko
github_username: coingecko
theme: minima
plugins:
- jekyll-feed
sass:
  style: compressed
autoprefixer:
  browsers:
  - last 4 versions
